
services:
    nginx:
            container_name: nginx
            restart: always
            build: ./nginx
            ports:
                - 100:100
            volumes:
                - static_volume:/usr/src/app/staticfiles/
            depends_on:
                - wsgiserver
                - asgiserver

    frontend:
        build: 
        context: ./react_typescript_frontend
        dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - '3000:3000'
        expose:
            - 3000

    postgres:
        container_name: postgres
        restart: always
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./.env.db

    redis:
        container_name: redis
        image: redis:5
        restart: unless-stopped
        ports:
            - 6379:6379


    wsgiserver:
        build:            
            context: ./django-rest-backend
            dockerfile: Dockerfile
        container_name: wsgiserver
        restart: always
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 
        env_file:
            - ./.env
        volumes:
            - static_volume:/usr/src/app/staticfiles/
        links:
            - postgres
        expose:
            - 8000


    asgiserver:
        build:            
            context: ./django-channels-backend
            dockerfile: Dockerfile
        container_name: asgiserver
        restart: always
        command: daphne core.asgi:application -b 0.0.0.0 -p 9000
        env_file:
            - ./.env
        links:
            - redis
        expose:
            - 9000